name: disaster-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  - pip

  # Core scientific stack (Conda handles these best)
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - pytorch=2.1.2
  - torchvision=0.16.2

  # Pip-only packages
  - pip:
      # Core AI/ML
      - cerebras-cloud-sdk==1.7.0
      - google-generativeai==0.8.3
      - transformers==4.56.2
      - sentence-transformers==3.0.1

      # Web Framework
      - fastapi==0.115.0
      - uvicorn[standard]==0.32.0
      - streamlit==1.39.0
      - requests==2.32.3

      # Docker & Container Management
      - docker==7.1.0
      # docker-compose deprecated → use `docker compose` CLI plugin

      # Database
      - sqlalchemy==2.0.35
      - psycopg2-binary==2.9.9
      - redis==5.2.0

      # Data Processing
      - pillow==10.4.0
      - opencv-python==4.10.0.84

      # Visualization & UI
      - folium==0.18.0
      - plotly==5.24.1
      - streamlit-folium==0.22.0

      # Vector Database & RAG
      - chromadb==0.5.20
      - langchain==0.3.7
      - langchain-core==0.3.17
      - langchain-community==0.3.7

      # Utilities
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - aiofiles==24.1.0
      - pydantic==2.9.2

      # Testing
      - pytest==8.3.3
      - pytest-asyncio==0.24.0

      # Additional utilities
      - tenacity==9.0.0
      - httpx==0.27.2